### ISSUE TITLE
Hangs on "Initializing DirectOutput library..."

### ISSUE THREAD

**Issue by ryansonshine** [AZaps/Elite-Dangerous-X52-MFD#12]
![image](https://cloud.githubusercontent.com/assets/9534477/20118214/afc48646-a5d1-11e6-8f61-7f80d5cfe939.png)

**Comment by AZaps** [comment]
Hi, thanks for the notification hopefully I can help resolve it.

Someone on the [reddit thread](https://www.reddit.com/r/EliteDangerous/comments/59xpkk/x52_screen_usage_tool_journal_update/) on /r/EliteDangerous also had something similar to this issue. They never responded so I am unsure if the issue was resolved. 

Based that the DirectOutput library was loaded correctly I can rule out any file hierarchy issues which is good.

The user mentioned they only installed the drivers from Saitek and not the software also. I recommend downloading the drivers **and the software** from them. [Saitek Download Page](http://www.saitek.com/uk/down/drivers.php). Select Pro-Flight -> X52 Pro ->(Your operating system) -> Download Software. I still haven't received any confirmation if the X52 also works but I don't see why not. I believe the DirectOutput library is referencing something from within the software download package and that is why it is failing to initialize. I haven't had a chance to look into it so I don't have a concrete answer.

Let me know if this helped and resolved your issue. If not, I'll look into it more in depth closer to the weekend.

**Comment by ryansonshine** [comment]
Hey @AZaps , I have the X52 software and driver installed. I'm using a Saitek X52 (non-pro).

**Comment by AZaps** [comment]
OK, going to take a deeper look into it.

In the meantime, could you look to see if you have another folder?

Should be C:\Program Files\Saitek\DirectOutput

**Comment by ryansonshine** [comment]
I'll be back on my windows machine later today and will let you know.

**Comment by ryansonshine** [comment]
I do not have C:\Program Files\Saitek\DirectOutput

**Comment by AZaps** [comment]
Hopefully that's the issue! I'm going to attach the zip, it contains the Saitek folder, drop it into C:\Program Files. I did try installing the X52 software and it seems like that folder wasn't included which is surprising. 

[Saitek.zip](https://github.com/AZaps/Elite-Dangerous-X52-MFD/files/590978/Saitek.zip)

**Comment by ryansonshine** [comment]
I placed the zip file contents into my program files directory; Still hanging. Does it matter if I have the 64-bit drivers installed versus 32-bit? Also I'm wondering if it could be me not having my profile configured properly.

**Comment by AZaps** [comment]
I tried running the program even without the extra Saitek folder, just in case, and I was able to initialize the library. I guess after all that folder isn't necessary. 

De-compiling and reading into the DirectOutput library as to what is going on to initialize is beyond what I am capable of, so I don't think I could help you further unfortunately. I recommend PM'ing the user on reddit to see if they resolved their issue and if you could follow. 

I'm not sure what you mean by not having the profile configured correctly? 

This is a 64-bit program. I do believe it should work on 32 unless the library is doing something I'm unaware of causing this issue.

**Comment by fotis016** [comment]
Need help as well, tried everything you mentioned, still can't get the program to work. Are you sure that this should work on the non pro version? I'm on Windows 10 64bit.

**Comment by AZaps** [comment]
I had assumed that the non pro version would work as it uses the same software and screen. It seems that is not the case as others are having issues with the non pro version. 

I will download the non pro version software and try to see what is causing these issues. Those statements on the window are essentially being used as checks to see what is being loaded. Since that statement isn't even presenting a 'OK' or "FAIL" statement after, something is happening on the DirectOutput Saitek library side which I do not have access to and makes it more difficult to find a solution.

**Comment by AZaps** [comment]
Unfortunately I have some bad news. After looking again at the Saitek page for both the pro and non-pro, it looks like this will only be supported by the pro. The non pro version looks to only display the current profile and what button is being pressed. The pro version allows further customization.

I was under the assumption that both were identical but after closer inspection the non pro is also missing the dual scroll wheels which are needed to navigate through the pages. 

Thanks for going through the troubleshooting steps but I apologize that it won't work as I previously thought.

**Comment by fotis016** [comment]
No problem. I'm not bothered at all as I got this hotas for crazy cheap so it's ok for me.

**Comment by AZaps** [comment]
I'm going to close this issue and put a disclaimer that only the X52 Pro will be supported by this tool, not the X52. 

Thanks for help with the troubleshooting.

**Comment by dougestey** [comment]
Super sad to hear about this :( time to trade my X-52 for a Pro.
